matrix:
  include:
    -language: node_js
    node_js:
    - '10'
    before_install:
    - cd frontend
    install:
    - yarn install
    script:
    - ./node_modules/.bin/eslint src 
    - yarn test --coverage --watchAll=false 
    -language: python
    cache:
      pip: true
      python: 3.7
    before_install:
      - cd backend
    install: 
      - pip install --user django
      - pip install --user pylint
      - pip install --user coverage
    script: 
      - pylint **/*.py
      - coverage run --source='./' --omit='manage.py, *wsgi*' manage.py test 
      - coverage report -m