matrix:
  include:
  - language: node_js
    node_js:
    - '10'
    dist: trusty
    addons:
        sonarcloud:
            organization: swsnu
            token:
                secure: TQIg4b20lPC8lhkixOEfDLZCC3ryLlQq7+f/nJhon2ACPwmjvLNjARrSlJ99yg7AUw7n2+0/qwbWSJxVppSbmhxaAEL3cSIdFEOzsrNbTRs2RRvqO82/WKmqjGknrYrNlcpqgNBZD8goEg9uEYM4fFT000E2p/pRtTCXMvc3fIADojLif08bplSiuCP9xXuzwe7tcwu3D0YaVHNpJoI4gSW/+kdRH3Cq4OEV3AzgzHHJ1kaa98aSZlYp/jqEsjgyWDssPzreMQvnnAXFmju6PtNFyyLZEZXrwK8WGWXhd+dX94ddbKM6d95kCbm1CDZixuprVbkTX0JuK3OuxPhPCx+ukZH8TFs7lU2fXDD3LVGBf0T6I7OA+Wc6mXZ438rMyNw9M8UZ+pf5gVgrqPo6WCn2gwhoGDeyBjiIBm7QX8QIYiY6wuyItqRDVjENYg667w90FzsuVuLeON06KjLul02vzdwl4OtIPwxtDHGbt5qjV1zQ4+UN1/t9SUXW+Bb/E5Grfo/x+D96efNTZCgSSIxh8X2nrk2HNk5WnjLDRKzFn6yg79p4tWepIGHE5p6l4MokBFaIbXbL4/lOv4L99ZNar+WCm3i9Ec7w9R4BMUGSHQrUjlm2cajuxZlqw6E8gBV10DBbmzsQVuDkrdghvm7jkT72XZKIUh1pmWdeGVE=
    before_install:
    - cd frontend
    install:
    - yarn install
    - yarn add coveralls
    script:
    - ./node_modules/.bin/eslint src --fix
    - yarn test --coverage --watchAll=false
    - sonar-scanner
    after_success:
    - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
    - cd ../
  - language: python
    cache:
      pip: true
      python: 3.7
    env:
    - DJANGO_VERSION=2.2.6
    before_script:
    - cd backend
    - python3 manage.py migrate
    install:
    - pip install  -q django==$DJANGO_VERSION
    - pip install  coverage
    - pip install  pylint
    - pip install -r ./requirements.txt
    - pip install coveralls
    script:
    - python --version
    - python -m django --version
    - pylint --load-plugins pylint_django **/*.py
    - coverage run --source='./' --omit='manage.py, *wsgi*' manage.py test
    - coverage report -m
    after_success:
    - coveralls
