# Generated by Django 2.2.5 on 2019-10-31 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='pill',
        ),
    ]
