# Generated by Django 2.2.5 on 2019-10-31 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pill', '0001_initial'),
        ('vision', '0002_remove_image_pill'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='pill',
            field=models.ForeignKey(default=1000, on_delete=django.db.models.deletion.CASCADE, to='pill.Pill'),
            preserve_default=False,
        ),
    ]
