# Generated by Django 2.2.5 on 2019-11-01 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0003_image_pill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='content',
            field=models.ImageField(default='image/default_pill_image.png', upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='pill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pill.Pill'),
        ),
        migrations.AlterField(
            model_name='image',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
