# Generated by Django 2.2.6 on 2019-10-19 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('take_method', models.TextField()),
                ('product_name', models.TextField()),
                ('expiration_date', models.TextField()),
                ('functions', models.TextField()),
                ('store_method', models.TextField()),
                ('company_name', models.TextField()),
                ('standards', models.TextField()),
                ('precautions', models.TextField()),
            ],
        ),
    ]
