# Generated by Django 2.2.6 on 2019-10-19 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xmlParser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pill',
            name='company_name',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='pill',
            name='expiration_date',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='pill',
            name='functions',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='pill',
            name='precautions',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='pill',
            name='product_name',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='pill',
            name='standards',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='pill',
            name='store_method',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='pill',
            name='take_method',
            field=models.TextField(default='', null=True),
        ),
    ]
