# Generated by Django 2.2.5 on 2019-11-18 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotiSetting',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='notiSetting', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('enable_noti', models.BooleanField(default=True)),
                ('enable_segregate', models.BooleanField(default=False)),
                ('enable_kakao', models.BooleanField(default=False)),
            ],
        ),
    ]
