# Generated by Django 2.2.6 on 2019-11-15 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('take_method', models.TextField(default='', null=True)),
                ('product_name', models.TextField(default='', null=True)),
                ('expiration_date', models.TextField(default='', null=True)),
                ('functions', models.TextField(default='', null=True)),
                ('store_method', models.TextField(default='', null=True)),
                ('company_name', models.TextField(default='', null=True)),
                ('standards', models.TextField(default='', null=True)),
                ('precautions', models.TextField(default='', null=True)),
                ('take_method_preprocessed', models.TextField(default='', null=True)),
            ],
        ),
    ]
