# Generated by Django 2.2.5 on 2019-11-02 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pill', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pill',
            name='take_method_preprocessed',
            field=models.TextField(default='', null=True),
        ),
    ]
