# Generated by Django 2.2.5 on 2019-11-06 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pill', '0002_pill_take_method_preprocessed'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pills',
            field=models.ManyToManyField(related_name='pills', to='pill.Pill'),
        ),
    ]
