# Generated by Django 2.2.5 on 2019-11-13 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_pills'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='telegram_id'),
        ),
    ]
