# Generated by Django 2.2.5 on 2019-11-10 07:57

import annoying.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_pills'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotiSetting',
            fields=[
                ('user', annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('enable', models.BooleanField(default=True)),
                ('enable_segregate', models.BooleanField(default=False)),
                ('enable_kakao', models.BooleanField(default=False)),
            ],
        ),
    ]
