# Generated by Django 2.2.5 on 2019-11-13 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_telegram_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='telegram_id',
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_first_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='telegram_first_name'),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_last_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='telegram_last_name'),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=100, verbose_name='telegram_username'),
        ),
    ]
