# Generated by Django 2.2.5 on 2019-11-10 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20191110_0829'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notisetting',
            old_name='enable',
            new_name='enable_noti',
        ),
        migrations.AlterField(
            model_name='notisetting',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='notiSetting', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
