# Generated by Django 2.2.5 on 2019-11-10 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20191110_1619'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotiSetting',
        ),
    ]
