# Generated by Django 2.2.5 on 2019-11-14 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activated', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(blank='09:00')),
            ],
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_username', models.TextField(default='', max_length=128)),
                ('telegram_first_name', models.TextField(default='', max_length=128)),
                ('telegram_last_name', models.TextField(default='', max_length=128)),
                ('auth_key', models.TextField(default='', max_length=128)),
                ('is_authenticated', models.BooleanField(default=False)),
                ('chat_id', models.IntegerField(default=-1)),
            ],
        ),
    ]
