# Generated by Django 2.2.5 on 2019-11-13 04:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pill', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activated', models.BooleanField(default=True)),
                ('pill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pill.Pill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_username', models.TextField(default='', max_length=128)),
                ('telegram_first_name', models.TextField(default='', max_length=128)),
                ('telegram_last_name', models.TextField(default='', max_length=128)),
                ('auth_key', models.TextField(default='', max_length=128)),
                ('is_authenticated', models.BooleanField(default=False)),
                ('chat_id', models.IntegerField(default=-1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(blank='09:00')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notification.Notification')),
            ],
        ),
    ]
