# Generated by Django 2.2.5 on 2019-11-11 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webnotification',
            name='notification_time',
        ),
        migrations.CreateModel(
            name='NotificationTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(blank='09:00')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notification.WebNotification')),
            ],
        ),
    ]
