# Generated by Django 2.2.5 on 2019-11-15 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_auto_20191115_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationtime',
            name='notification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notitime', to='notification.Notification'),
        ),
    ]
