# Generated by Django 2.2.5 on 2019-11-13 04:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notification', '0002_auto_20191111_0915'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_username', models.TextField(default='', max_length=128)),
                ('telegram_first_name', models.TextField(default='', max_length=128)),
                ('telegram_last_name', models.TextField(default='', max_length=128)),
                ('auth_key', models.TextField(default='', max_length=128)),
                ('is_authenticated', models.BooleanField(default=False)),
                ('chat_id', models.IntegerField(default=-1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
